//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBackend.Application.Resources.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreBackend.Application.Resources.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kaynağa erişim yasak..
        /// </summary>
        public static string AUTH_FORBIDDEN_ACCESS {
            get {
                return ResourceManager.GetString("AUTH_FORBIDDEN_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kullanıcı adı veya şifre..
        /// </summary>
        public static string AUTH_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("AUTH_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum süresi doldu..
        /// </summary>
        public static string AUTH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz oturum bilgisi..
        /// </summary>
        public static string AUTH_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkisiz erişim denemesi..
        /// </summary>
        public static string AUTH_UNAUTHORIZED_ACCESS {
            get {
                return ResourceManager.GetString("AUTH_UNAUTHORIZED_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı hesabı kilitli..
        /// </summary>
        public static string AUTH_USER_LOCKED {
            get {
                return ResourceManager.GetString("AUTH_USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        public static string AUTH_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("AUTH_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu şirket zaten kayıtlı..
        /// </summary>
        public static string COMPANY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("COMPANY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket pasif durumda..
        /// </summary>
        public static string COMPANY_INACTIVE {
            get {
                return ResourceManager.GetString("COMPANY_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz şirket erişimi..
        /// </summary>
        public static string COMPANY_INVALID_ACCESS {
            get {
                return ResourceManager.GetString("COMPANY_INVALID_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz vergi numarası formatı..
        /// </summary>
        public static string COMPANY_INVALID_TAX_NUMBER {
            get {
                return ResourceManager.GetString("COMPANY_INVALID_TAX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket bulunamadı..
        /// </summary>
        public static string COMPANY_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMPANY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut durumla bir çakışma oluştu..
        /// </summary>
        public static string GENERAL_CONFLICT {
            get {
                return ResourceManager.GetString("GENERAL_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem geçerli değil..
        /// </summary>
        public static string GENERAL_INVALID_OPERATION {
            get {
                return ResourceManager.GetString("GENERAL_INVALID_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenen kayıt bulunamadı..
        /// </summary>
        public static string GENERAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENERAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli bir değer sağlanmadı..
        /// </summary>
        public static string GENERAL_NULL_VALUE {
            get {
                return ResourceManager.GetString("GENERAL_NULL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen bir hata oluştu..
        /// </summary>
        public static string GENERAL_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir veya daha fazla doğrulama hatası oluştu..
        /// </summary>
        public static string GENERAL_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu tenant zaten kayıtlı..
        /// </summary>
        public static string TENANT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("TENANT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant hesabı pasif durumda..
        /// </summary>
        public static string TENANT_INACTIVE {
            get {
                return ResourceManager.GetString("TENANT_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz tenant erişimi..
        /// </summary>
        public static string TENANT_INVALID_ACCESS {
            get {
                return ResourceManager.GetString("TENANT_INVALID_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant bulunamadı..
        /// </summary>
        public static string TENANT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TENANT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant hesabı askıya alınmış..
        /// </summary>
        public static string TENANT_SUSPENDED {
            get {
                return ResourceManager.GetString("TENANT_SUSPENDED", resourceCulture);
            }
        }
    }
}
